### ISSUE TITLE
Using default HTML element <a> to reach out routes

### ISSUE THREAD

**Issue by baptistebriel** [bigwheel-framework/bigwheel#12]
Hello!

This is not a real issue, but a discussion on best practices when using bigwheel that could lead to possible improvements.

It would be awesome if we could use the default HTML element <a> to reach another route, instead of using addEventListener / onclick event on sections' "init". This would prevent useless code I think.

What seems tricky is to get all <a> elements and even those that were added to the DOM after an ajax call (for example). I usually do an ajax request on "init" for the template file of the section; therefore the events needs to be attached on the success callback.

We would also need a default attribute for preventing external links to be treated like route links. Maybe just using target="_blank" would do the trick?

What do you think?

Loving bigwheel so far, very nice job !

**Comment by MikkoH** [comment]
Thanks.

Generally how we work at Jam3 is yes an init we load Ajax load some content (generally JSON) and then we template using either vue or handlebars. Although I need to look at react cause it will work nicely with bigwheel. Anyway after all the dom has been setup we'll go in and select specific elements we'll need to animate or add event listeners to.

Since hash bang urls are used there's no reason why you cant do something like:
`<a href="#!/yourRoute/here">your button name</a>`

And then obviously just style through css.

We've been talking about building a controller of sorts which could be used to load in templates, models, etc. @njam3 will be working on that most likely.

I'm not sure I follow:
`We would also need a default attribute for preventing external links to be treated like route links. Maybe just using target="_blank" would do the trick?`

Glad you're enjoying bigwheel. It does take a bit of time to learn all the tricks and we've been using it for a long time now so feel free to ping via issues.

**Comment by baptistebriel** [comment]
In my head I was thinking of selecting every <a> elements and just call `framework.go(this.getAttribute('href'))` on click... Haha.

*"Keep it simple, stupid."*

Using the hash bang in the href attribute will just work nicely. :)
Thank you for your time and best practices!

**Comment by MikkoH** [comment]
It's a tough line to balance. When I first started writing bigwheel I was gonna write every bell and whistle into it. And then I pulled back and thought this really should be a very modular project. Let bigwheel do what it's good at. Manage the state of the application. Let other modules do what they do well (templating, handling the model, selecting dom elements, etc.)

So that's where it's headed. The next feature I want to add is something like:
```
var subFramework = framework.sub( {
  routes: {
    '/:galleryItem': require('../sections/galleryItem')
  }
});
```

This would allow for things like galleries where one framework is handling the main routes. And then you have a second framework which handles for instance bringing in out items for a gallery. "sub items"

**Comment by baptistebriel** [comment]
Sure, specially when using npm (or any other package manager) where each package is dedicated to something precise. After some projects using page.js and other tiny JavaScript routers, I actually just needed something to manage the state of my site or app without having to go "under the hood", so I could just focus on what's really important.

I've actually seen this on #3 — If I understand what you're saying, you want another 'framework' that doesn't conflict with the main one so we could use it for 'layered' sections while the main routes/sections doesn't change? This would be useful when you want to 'open a route' but doesn't want the current one to be destroyed? I'd use it for sure! :)

**Comment by MikkoH** [comment]
Yep exactly. Maybe I just need to go on vaca to get it written ;) (last time I was on vaca I wrote bigwheel) Up until that point we were using a very similar framework but with bigwheel we open sourced it and I cleaned up some parts mainly the router.

**Comment by baptistebriel** [comment]
Cool, would definitely need that. I had a use case using page.js where I had a grid portfolio and wanted to open the project page without 'fading' or removing the grid. I had to come with an ugly hack...
Didn't you had any vacations since December 2014?! You definitely should get some! But that's not what vacations are made for anyway ;)
